data\_cleaning
================
Zongchao
4/26/2021

# Import data & cleaning

``` r
data = read_excel('./data/家长问卷_刘宗超.xlsx') %>%
    .[-1,]  %>% 
  select(8,9,12:127) %>%
  group_by(ID) %>%
  mutate(keep = ifelse(missing == min(missing), "keep", "drop")) %>%
  select(keep, everything())
length(unique(data$ID))
```

    ## [1] 316

``` r
# 检查数据
## 出生年处理策略：集中处理-2 -> 取前4个字符 -> 然后处理 "199元"，“4月10日”，“不知道”，"57"
data[data == -2] = "NA"
unique(data$p4)
```

    ##  [1] "1986"          "NA"            "1978"          "1989"         
    ##  [5] "1951"          "1990"          "1969"          "1962"         
    ##  [9] "1959"          "1956"          "1980年"        "1980"         
    ## [13] "1949"          "1982"          "1964"          "1993"         
    ## [17] "1979"          "1985"          "1977"          "1965"         
    ## [21] "1966"          "2000"          "1974"          "1970"         
    ## [25] "1976"          "1963"          "1958"          "1988"         
    ## [29] "1987"          "1983"          "2011"          "1971"         
    ## [33] "1986年"        "2020"          "1995"          "1995年"       
    ## [37] "1983年"        "1968"          "1968年"        "1981"         
    ## [41] "1992年"        "1992"          "1954"          "1961"         
    ## [45] "1955"          "1991"          "2012"          "2009"         
    ## [49] "2007"          "2010"          "不知道"        "2008"         
    ## [53] "1975"          "19910"         "1984"          "1936"         
    ## [57] "'200906174677" "4月10日"       "1973"          "1967"         
    ## [61] "1956.3.22"     "1997"          "1952"          "1988.1"       
    ## [65] "1995年6月7日"  "1990.9.1"      "1943"          "199元"        
    ## [69] "1985.11.30"    "1978年2月1日"  "1987.10.26"    "57"           
    ## [73] "1988.3.16"     "1950"          "1972"          "1960"

``` r
## p35处理策略：无需处理
unique(data$p36)
```

    ##  [1] "20"             "7"              "3"              "5"             
    ##  [5] "三间两层"       "6"              "8"              "NA"            
    ##  [9] "4"              "三室一厅"       "10"             "15"            
    ## [13] "9"              "16"             "12"             "11"            
    ## [17] "8-9"            "14"             "2"              "13"            
    ## [21] "39"             "18"             "1厅"            "200平"         
    ## [25] "12间加一间茅房" "9个"            "15个"           "四室一厅"      
    ## [29] "6个"            "没有客厅4间房"  "七"             "5-6个"         
    ## [33] "31"             "35（？）"       "35"             "4间"

``` r
# 处理异常值 -  此处需要根据自己情况DIY！
data = data %>%
  mutate(p4 = ifelse(p4 == "NA", "NA", p4)) %>%
  mutate(p4 = case_when(p4 %in% c("199元","4月10日","不知道","57", "'200906174677") == FALSE ~ p4,
                        p4 == "199元" ~ "1992",
                        p4 == "不知道" ~ "NA",
                        p4 == "57" ~ "??57",
                        p4 == "4月10日" ~ "NA",
                        p4 == "'200906174677" ~ "2009")) %>%
  mutate(p4 = str_sub(p4, 1, 4)) %>%
  mutate(p36 = ifelse(p36 == "NA", "NA", p36),
         p36 = case_when(p36 == "三间两层" ~ "3",
                         p36 == "三室一厅" ~ "4",
                         p36 == "8-9" ~ "8",
                         p36 == "12间加一间茅房" ~ "12",
                         p36 == "四室一厅" ~ "5",
                         p36 == "七" ~ "7",
                         p36 == "5-6个" ~ "5",
                         p36 == "没有客厅4间房" ~ "4",
                         p36 %in% c("三间两层","三室一厅", "8-9", "12间加一间茅房", "四室一厅",
                                    "七", "5-6个", "没有客厅4间房") == FALSE ~ p36
                         ),
         p36 = str_remove_all(p36, "[个间]")) 

# 开始删行
## 填补规则：对一个人的多条记录，在保留原始missing数最少的记录的基础上进行填补。
## 填补时存在以下几种情况：
## 1. a,b两（或多）条记录missing数不等,且a缺失数>b, 则保留b，通过a填补b。
## 2. a,b两（或多）条记录missing数相等,则同时互补a,b，保留并集。
## 2. a,b两（或多）条记录missing数为0,则任意保留a,b其中一条。

imp_data = data %>%
  group_by(ID, missing) %>% 
  fill(everything(), .direction = "up") %>% 
  fill(everything(), .direction = "down") %>%
  #先从下往上填补，再从上往下填补。这样保证了以misssing数最少的条目为基础来进行填补。这个操作对多个missing数相同，同ID的条目无影响；对同一个ID，但其中有missing数为0的条目来说，相当于先用missing为0的去填补
  group_by(ID) %>%
  slice_min(missing) %>%
  #filter(keep == "keep") %>%
  group_by(ID) %>%
  slice(1)

imp_data[imp_data == "NA"] = NA
```

# 检查结果

## 检查值

``` r
# 检查样本量- True: 一致
length(unique(data$ID)) == nrow(imp_data)
```

    ## [1] TRUE

``` r
# 检查日期值 集合
unique(imp_data$p4)
```

    ##  [1] "1961" "1987" "1967" "1982" "1991" "1963" NA     "1983" "1964" "1989"
    ## [11] "1980" "1960" "1985" "2010" "1979" "1988" "1990" "1993" "1972" "1962"
    ## [21] "1974" "1981" "1992" "1950" "1986" "1958" "??57" "1976" "1966" "1973"
    ## [31] "1978" "1975" "1954" "1984" "1943" "1995" "1952" "1997" "1956" "1969"
    ## [41] "2008" "2009" "1936" "1970" "1971" "1977" "1965" "2007" "2012" "1955"
    ## [51] "1951" "1968" "2011" "2020" "1959" "1949"

``` r
# 检查房间数 集合，我认为特殊的值没有做清洗
unique(imp_data$p36)
```

    ##  [1] "20"       "8"        "5"        "3"        "9"        "15"      
    ##  [7] "4"        "6"        "7"        "14"       NA         "10"      
    ## [13] "35（？）" "31"       "18"       "2"        "13"       "12"      
    ## [19] "11"       "200平"    "1厅"      "16"

## 检查是否填补

``` r
missing_imp = cbind(imp_data$ID, rowSums(is.na(imp_data))) %>% as.data.frame() %>%
  rename("ID" = "V1", "missing_imp" = V2)

missing_original = data %>%
  group_by(ID) %>%
  summarise(missing_min = min(missing)) %>%
  arrange(ID)
```

    ## `summarise()` ungrouping output (override with `.groups` argument)

``` r
# 在check res表格中，若 expected 为 TRUE 代表填补无问题，若为FALSE则根据ID，回到excel表格检查具体数据情况
check_res = left_join(missing_imp, missing_original) %>%
  mutate(missing_imp = as.numeric(as.character(missing_imp)),
         missing_min = as.numeric(as.character(missing_min))) %>%
  mutate(expected = ifelse(missing_imp <= missing_min, TRUE, FALSE))
```

    ## Joining, by = "ID"

``` r
knitr::kable(check_res)
```

| ID       | missing\_imp | missing\_min | expected |
| :------- | -----------: | -----------: | :------- |
| 12242739 |            2 |            2 | TRUE     |
| 12243226 |            5 |            5 | TRUE     |
| 12243440 |            0 |            0 | TRUE     |
| 12243824 |            5 |            5 | TRUE     |
| 12244115 |            0 |            0 | TRUE     |
| 12244547 |            0 |            0 | TRUE     |
| 12245218 |            2 |            2 | TRUE     |
| 12245635 |            7 |            7 | TRUE     |
| 12245920 |            0 |            0 | TRUE     |
| 12246112 |            3 |            3 | TRUE     |
| 12246130 |            7 |            7 | TRUE     |
| 12246714 |            3 |            3 | TRUE     |
| 12246842 |            0 |            0 | TRUE     |
| 12247134 |            1 |            1 | TRUE     |
| 12247717 |            6 |            6 | TRUE     |
| 12247729 |            6 |            6 | TRUE     |
| 12247732 |            6 |            6 | TRUE     |
| 12248145 |            1 |            1 | TRUE     |
| 12248549 |            6 |            6 | TRUE     |
| 12248848 |            2 |            2 | TRUE     |
| 12249211 |            4 |            4 | TRUE     |
| 12249628 |            2 |            2 | TRUE     |
| 12249840 |            2 |            2 | TRUE     |
| 12251244 |            0 |            0 | TRUE     |
| 12251326 |            0 |            0 | TRUE     |
| 12251912 |            0 |            0 | TRUE     |
| 12252718 |            2 |            2 | TRUE     |
| 12252720 |            0 |            0 | TRUE     |
| 12252840 |            1 |            1 | TRUE     |
| 12253133 |            0 |            0 | TRUE     |
| 12253139 |           37 |           37 | TRUE     |
| 12253714 |           18 |           18 | TRUE     |
| 12254613 |            4 |            5 | TRUE     |
| 12255942 |            0 |            0 | TRUE     |
| 12256128 |            0 |            0 | TRUE     |
| 12256217 |            4 |            4 | TRUE     |
| 12256422 |            6 |            6 | TRUE     |
| 12256731 |            0 |            0 | TRUE     |
| 12256738 |            0 |            0 | TRUE     |
| 12256947 |            0 |            0 | TRUE     |
| 12257429 |            2 |            2 | TRUE     |
| 12257846 |            1 |            1 | TRUE     |
| 12258145 |            0 |            0 | TRUE     |
| 12258711 |            2 |            2 | TRUE     |
| 12258727 |            4 |            4 | TRUE     |
| 12259434 |            1 |            1 | TRUE     |
| 12262518 |            0 |            0 | TRUE     |
| 12263615 |            3 |            3 | TRUE     |
| 12263920 |            3 |            3 | TRUE     |
| 12264132 |            7 |            7 | TRUE     |
| 12264324 |            0 |            0 | TRUE     |
| 12264713 |            0 |            0 | TRUE     |
| 12265216 |            6 |            6 | TRUE     |
| 12265321 |            0 |            0 | TRUE     |
| 12265334 |            1 |            1 | TRUE     |
| 12265528 |            5 |            5 | TRUE     |
| 12265544 |            4 |            4 | TRUE     |
| 12265931 |            0 |            0 | TRUE     |
| 12266145 |            1 |            1 | TRUE     |
| 12266246 |            0 |            0 | TRUE     |
| 12266722 |            2 |            2 | TRUE     |
| 12266727 |            1 |            1 | TRUE     |
| 12266929 |            1 |            1 | TRUE     |
| 12267233 |            0 |            0 | TRUE     |
| 12267923 |           12 |           12 | TRUE     |
| 12268414 |           46 |           46 | TRUE     |
| 12268512 |            9 |            9 | TRUE     |
| 12269647 |           17 |           17 | TRUE     |
| 12271543 |            2 |            2 | TRUE     |
| 12272225 |            1 |            1 | TRUE     |
| 12272316 |            2 |            2 | TRUE     |
| 12272551 |            0 |            0 | TRUE     |
| 12272638 |            0 |            0 | TRUE     |
| 12272745 |            1 |            1 | TRUE     |
| 12273328 |            0 |            0 | TRUE     |
| 12273754 |            2 |            2 | TRUE     |
| 12273831 |            0 |            0 | TRUE     |
| 12274144 |            6 |            6 | TRUE     |
| 12274714 |            3 |            3 | TRUE     |
| 12275320 |            1 |            1 | TRUE     |
| 12275750 |            0 |            0 | TRUE     |
| 12275915 |            0 |            0 | TRUE     |
| 12276122 |            2 |            2 | TRUE     |
| 12276248 |            1 |            1 | TRUE     |
| 12277240 |            2 |            2 | TRUE     |
| 12277427 |            0 |            0 | TRUE     |
| 12277617 |            1 |            1 | TRUE     |
| 12278355 |            0 |            0 | TRUE     |
| 12278523 |            1 |            1 | TRUE     |
| 12278547 |            1 |            1 | TRUE     |
| 12279549 |            0 |            0 | TRUE     |
| 12281336 |            0 |            0 | TRUE     |
| 12281527 |            0 |            0 | TRUE     |
| 12281845 |            4 |            4 | TRUE     |
| 12281946 |            6 |            6 | TRUE     |
| 12282623 |            0 |            0 | TRUE     |
| 12282648 |            1 |            1 | TRUE     |
| 12282928 |            1 |            2 | TRUE     |
| 12283331 |            0 |            0 | TRUE     |
| 12283341 |            5 |            5 | TRUE     |
| 12283716 |           10 |           10 | TRUE     |
| 12284735 |            2 |            2 | TRUE     |
| 12285419 |            0 |            0 | TRUE     |
| 12286249 |            2 |            2 | TRUE     |
| 12286733 |            0 |            0 | TRUE     |
| 12287220 |            0 |            0 | TRUE     |
| 12288418 |            3 |            3 | TRUE     |
| 12288515 |            3 |            3 | TRUE     |
| 12288639 |            4 |            4 | TRUE     |
| 12288713 |            1 |            1 | TRUE     |
| 12288942 |            0 |            0 | TRUE     |
| 12289534 |            1 |            1 | TRUE     |
| 12289614 |            5 |            5 | TRUE     |
| 12291528 |            2 |            2 | TRUE     |
| 12291643 |            0 |            0 | TRUE     |
| 12291917 |            0 |            0 | TRUE     |
| 12292115 |            0 |            0 | TRUE     |
| 12292146 |            0 |            0 | TRUE     |
| 12292548 |            1 |            1 | TRUE     |
| 12292924 |            2 |            2 | TRUE     |
| 12293518 |           11 |           11 | TRUE     |
| 12294238 |            6 |            6 | TRUE     |
| 12294619 |            1 |            1 | TRUE     |
| 12294826 |            0 |            0 | TRUE     |
| 12294833 |            0 |            0 | TRUE     |
| 12295729 |           21 |           21 | TRUE     |
| 12295825 |            3 |            3 | TRUE     |
| 12296130 |            9 |            8 | FALSE    |
| 12296235 |            0 |            0 | TRUE     |
| 12296322 |            0 |            0 | TRUE     |
| 12296445 |            2 |            2 | TRUE     |
| 12296612 |            0 |            0 | TRUE     |
| 12296813 |            1 |            1 | TRUE     |
| 12296842 |            1 |            1 | TRUE     |
| 12296911 |            3 |            3 | TRUE     |
| 12297144 |            0 |            0 | TRUE     |
| 12298214 |           10 |           10 | TRUE     |
| 12298234 |            8 |            8 | TRUE     |
| 12298247 |            1 |            1 | TRUE     |
| 12298431 |            0 |            0 | TRUE     |
| 12298732 |            0 |            0 | TRUE     |
| 12298936 |            0 |            0 | TRUE     |
| 12299121 |           18 |           18 | TRUE     |
| 12299327 |            0 |            0 | TRUE     |
| 12299340 |            0 |            0 | TRUE     |
| 12299616 |           10 |           10 | TRUE     |
| 12299639 |            0 |            0 | TRUE     |
| 12299641 |            1 |            1 | TRUE     |
| 13311125 |            1 |            1 | TRUE     |
| 13311822 |            1 |            2 | TRUE     |
| 13311827 |           43 |           43 | TRUE     |
| 13312217 |            0 |            0 | TRUE     |
| 13312230 |            3 |            3 | TRUE     |
| 13312524 |           44 |           44 | TRUE     |
| 13312538 |           43 |           44 | TRUE     |
| 13312642 |            2 |            2 | TRUE     |
| 13312911 |            3 |            3 | TRUE     |
| 13313326 |            1 |            1 | TRUE     |
| 13313532 |            2 |            2 | TRUE     |
| 13313634 |            6 |            6 | TRUE     |
| 13313640 |            3 |            3 | TRUE     |
| 13314721 |            3 |            3 | TRUE     |
| 13314912 |            0 |            0 | TRUE     |
| 13315115 |            2 |            2 | TRUE     |
| 13315720 |            0 |            0 | TRUE     |
| 13316435 |            2 |            2 | TRUE     |
| 13316941 |            2 |            3 | TRUE     |
| 13317419 |            8 |            8 | TRUE     |
| 13317523 |            0 |            0 | TRUE     |
| 13317933 |            0 |            0 | TRUE     |
| 13318431 |           45 |           45 | TRUE     |
| 13318616 |           13 |           13 | TRUE     |
| 13321519 |            2 |            2 | TRUE     |
| 13322823 |            0 |            0 | TRUE     |
| 13322917 |            1 |            1 | TRUE     |
| 13322920 |            3 |            3 | TRUE     |
| 13323122 |            3 |            3 | TRUE     |
| 13323528 |            6 |            6 | TRUE     |
| 13324714 |            1 |            0 | FALSE    |
| 13324731 |            0 |            0 | TRUE     |
| 13324735 |            2 |            2 | TRUE     |
| 13324930 |           10 |           10 | TRUE     |
| 13325333 |            5 |            5 | TRUE     |
| 13325436 |            2 |            2 | TRUE     |
| 13325437 |            6 |            6 | TRUE     |
| 13325440 |            6 |            6 | TRUE     |
| 13325711 |            0 |            0 | TRUE     |
| 13326141 |            1 |            1 | TRUE     |
| 13326618 |            0 |            0 | TRUE     |
| 13327734 |            1 |            1 | TRUE     |
| 13328226 |            0 |            0 | TRUE     |
| 13328715 |            0 |            0 | TRUE     |
| 13328927 |            5 |            5 | TRUE     |
| 13331822 |            0 |            0 | TRUE     |
| 13332311 |            1 |            1 | TRUE     |
| 13332314 |            0 |            0 | TRUE     |
| 13332363 |            3 |            3 | TRUE     |
| 13332618 |            2 |            2 | TRUE     |
| 13332734 |            0 |            0 | TRUE     |
| 13332735 |            0 |            0 | TRUE     |
| 13333621 |            2 |            2 | TRUE     |
| 13333937 |            2 |            2 | TRUE     |
| 13334536 |            0 |            0 | TRUE     |
| 13334833 |            0 |            0 | TRUE     |
| 13335413 |            0 |            0 | TRUE     |
| 13335539 |            5 |            5 | TRUE     |
| 13335928 |            4 |            4 | TRUE     |
| 13335930 |            8 |            8 | TRUE     |
| 13336916 |            0 |            0 | TRUE     |
| 13337527 |            0 |            0 | TRUE     |
| 13337815 |            1 |            1 | TRUE     |
| 13337912 |            0 |            0 | TRUE     |
| 13337942 |            0 |            0 | TRUE     |
| 13339320 |            2 |            2 | TRUE     |
| 13339529 |            0 |            0 | TRUE     |
| 13339538 |            1 |            1 | TRUE     |
| 13339626 |            0 |            0 | TRUE     |
| 14411111 |            0 |            0 | TRUE     |
| 14411617 |           16 |           16 | TRUE     |
| 14411749 |            0 |            0 | TRUE     |
| 14411945 |            3 |            3 | TRUE     |
| 14412212 |            1 |            1 | TRUE     |
| 14412947 |            0 |            0 | TRUE     |
| 14413343 |            4 |            4 | TRUE     |
| 14414121 |            2 |            2 | TRUE     |
| 14414240 |            1 |            1 | TRUE     |
| 14414816 |            1 |            1 | TRUE     |
| 14414831 |            4 |            4 | TRUE     |
| 14415844 |            0 |            0 | TRUE     |
| 14416314 |            0 |            0 | TRUE     |
| 14416436 |            1 |            1 | TRUE     |
| 14416522 |           45 |           45 | TRUE     |
| 14416823 |            1 |            1 | TRUE     |
| 14417218 |            3 |            3 | TRUE     |
| 14417752 |            0 |            0 | TRUE     |
| 14418313 |            0 |            0 | TRUE     |
| 14418641 |            1 |            1 | TRUE     |
| 14418837 |            2 |            2 | TRUE     |
| 14419126 |            0 |            0 | TRUE     |
| 14421236 |            3 |            3 | TRUE     |
| 14421411 |            0 |            0 | TRUE     |
| 14421416 |           17 |           18 | TRUE     |
| 14421629 |            5 |            5 | TRUE     |
| 14421924 |            0 |            0 | TRUE     |
| 14422130 |            0 |            0 | TRUE     |
| 14422639 |            0 |            0 | TRUE     |
| 14423537 |            2 |            2 | TRUE     |
| 14423615 |            0 |            0 | TRUE     |
| 14423844 |            0 |            0 | TRUE     |
| 14426320 |            2 |            2 | TRUE     |
| 14426431 |            1 |            1 | TRUE     |
| 14426527 |            0 |            0 | TRUE     |
| 14426532 |            1 |            1 | TRUE     |
| 14426535 |            1 |            1 | TRUE     |
| 14426645 |            0 |            0 | TRUE     |
| 14427623 |            0 |            0 | TRUE     |
| 14427722 |            1 |            1 | TRUE     |
| 14427826 |           11 |           11 | TRUE     |
| 14427833 |            1 |            1 | TRUE     |
| 14427842 |            5 |            5 | TRUE     |
| 14427914 |            1 |            1 | TRUE     |
| 14428940 |            8 |            8 | TRUE     |
| 14431411 |            2 |            2 | TRUE     |
| 14431730 |            6 |            6 | TRUE     |
| 14431740 |            8 |            8 | TRUE     |
| 14432319 |            9 |            9 | TRUE     |
| 14432347 |            0 |            0 | TRUE     |
| 14432533 |           47 |           47 | TRUE     |
| 14432631 |            2 |            2 | TRUE     |
| 14432712 |            2 |            2 | TRUE     |
| 14432948 |            1 |            1 | TRUE     |
| 14433327 |            1 |            1 | TRUE     |
| 14433356 |            3 |            3 | TRUE     |
| 14433421 |            2 |            2 | TRUE     |
| 14433625 |           11 |           11 | TRUE     |
| 14433729 |           14 |           14 | TRUE     |
| 14433843 |            3 |            3 | TRUE     |
| 14434150 |            0 |            0 | TRUE     |
| 14434252 |            4 |            4 | TRUE     |
| 14434657 |            2 |            3 | TRUE     |
| 14435138 |            0 |            0 | TRUE     |
| 14435839 |            7 |            7 | TRUE     |
| 14435893 |            7 |            7 | TRUE     |
| 14436132 |            4 |            4 | TRUE     |
| 14437145 |            7 |            7 | TRUE     |
| 14437258 |            0 |            0 | TRUE     |
| 14437414 |            5 |            5 | TRUE     |
| 14437417 |            8 |            8 | TRUE     |
| 14437444 |            1 |            1 | TRUE     |
| 14438154 |            0 |            0 | TRUE     |
| 14438220 |           42 |           42 | TRUE     |
| 14438353 |            0 |            0 | TRUE     |
| 14438659 |            5 |            5 | TRUE     |
| 14438728 |            6 |            6 | TRUE     |
| 14439213 |            2 |            2 | TRUE     |
| 14439236 |           10 |           10 | TRUE     |
| 14439326 |            1 |            1 | TRUE     |
| 14439341 |            1 |            1 | TRUE     |
| 14439415 |            2 |            2 | TRUE     |
| 14439537 |           40 |           40 | TRUE     |
| 14439642 |            0 |            1 | TRUE     |
| 14441336 |            6 |            6 | TRUE     |
| 14441519 |            0 |            0 | TRUE     |
| 14442237 |            1 |            1 | TRUE     |
| 14442517 |            2 |            2 | TRUE     |
| 14442616 |            9 |            9 | TRUE     |
| 14443611 |           13 |           14 | TRUE     |
| 14443720 |            3 |            3 | TRUE     |
| 14444224 |            0 |            0 | TRUE     |
| 14444233 |            8 |            8 | TRUE     |
| 14444244 |            0 |            0 | TRUE     |
| 14444429 |            0 |            0 | TRUE     |
| 14445343 |            2 |            2 | TRUE     |
| 14445527 |            5 |            5 | TRUE     |
| 14445532 |            1 |            1 | TRUE     |
| 14445834 |            0 |            0 | TRUE     |

# 检查结果&导出

这一步基本只会排查出极少数需要具体纠察的记录，需要diy。

仅2条数据填补结果不符合要求（ID:13324714, 12296130），核查后发现是由于回答问卷的人操作不当所致，最终可以填补后的结果为准。

``` r
write.csv(imp_data, './问卷-已清理_刘宗超_20210427.csv',row.names = F)
```

# 填补过程

填补前的数据长这样：

``` r
data %>%
  group_by(ID, missing) %>% 
    head(10) %>%
  knitr::kable()
```

| keep | ID       | missing | p3 | p4   | p5 | p6 | p7 | p8 | p9 | p10 | p11 | p12 | p13 | p14 | p15 | p16 | p17 | p18 | p19 | p20 | p21 | p22 | p23a | p23b | p23c | p23d | p23e | p23f | p23g | p23h | p24a | p24b | p24c | p24d | p24e | p24f | p24g | p24h | p24i | p25 | p26 | p27a | p27b | p27c | p27d | p27e | p28 | p29 | p30 | p31 | p32 | p33 | p34 | p35 | p36 | p37 | p38a | p38b | p38c | p38d | p38e | p38f | p38g | p38h | p38i | p38j | p38k | p38l | p38m | p38n | p38o | p38p | p39 | p40 | p41 | p42 | p43 | p44 | p45a | p45b | p45c | p45d | p45e | p45f | p45g | p45h | p45i | p45j | p45k | p45l | p45m | p45n | p45o | p46 | p47 | p48a | p48b | p48c | p48d | p48e | p48f | p49 | p50a | p50b | p50c | p50d | p50e | p51a | p51b | p51c | p51d | p51e | p51f | p51g | p51h | p51i | p51j | p51k |
| :--- | :------- | ------: | :- | :--- | :- | :- | :- | :- | :- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :-- | :-- | :--- | :--- | :--- | :--- | :--- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :-- | :-- | :-- | :-- | :-- | :-- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :-- | :-- | :--- | :--- | :--- | :--- | :--- | :--- | :-- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| keep | 14445834 |       0 | 1  | 1986 | 1  | 1  | 3  | 5  | 5  | 1   | \-3 | \-3 | \-3 | \-3 | \-3 | \-3 | \-3 | 2   | 3   | 4   | 5   | 6   | 3    | 3    | 1    | 1    | 2    | 2    | 1    | 3    | 1    | 2    | 3    | 1    | 1    | 3    | 2    | 2    | 2    | 4   | 4   | 2    | 3    | 3    | 2    | 2    | 2   | 3   | 7   | 3   | 4   | 2   | 5   | 2   | 20  | 1   | 1    | 1    | 1    | 2    | 1    | 1    | 2    | 1    | 1    | 1    | 1    | 2    | 1    | 1    | 2    | 2    | 2   | 1   | 2   | 3   | 1   | 4   | 3    | 3    | 3    | 3    | 3    | 3    | 2    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 6   | 5   | 0    | 1    | 0    | 0    | 0    | 0    | 2   | 1    | 0    | 0    | 0    | 0    | 4    | 4    | 4    | 4    | 4    | 4    | 4    | 4    | 3    | 4    | 4    |
| keep | 14445834 |       0 | 1  | 1986 | 1  | 1  | 3  | 5  | 5  | 1   | \-3 | \-3 | \-3 | \-3 | \-3 | \-3 | \-3 | 2   | 3   | 5   | 5   | 6   | 3    | 3    | 1    | 1    | 2    | 2    | 1    | 3    | 1    | 2    | 3    | 1    | 1    | 3    | 2    | 2    | 2    | 4   | 4   | 2    | 3    | 3    | 2    | 2    | 2   | 3   | 7   | 3   | 4   | 2   | 5   | 2   | 20  | 1   | 1    | 1    | 1    | 2    | 1    | 1    | 2    | 1    | 1    | 1    | 1    | 2    | 1    | 1    | 2    | 2    | 2   | 1   | 2   | 3   | 1   | 4   | 3    | 3    | 3    | 3    | 3    | 3    | 2    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 6   | 5   | 0    | 1    | 0    | 0    | 0    | 0    | 2   | 1    | 0    | 0    | 0    | 0    | 4    | 4    | 4    | 4    | 4    | 4    | 4    | 4    | 3    | 4    | 4    |
| keep | 14445532 |       1 | 1  | NA   | 1  | 1  | 1  | 5  | 8  | 2   | 1   | 3   | 11  | \-3 | \-3 | \-3 | \-3 | 3   | 1   | 5   | 8   | 3   | 1    | 3    | 4    | 4    | 4    | 4    | 1    | 3    | 2    | 2    | 2    | 2    | 2    | 3    | 3    | 2    | 2    | 4   | 4   | 1    | 1    | 1    | 1    | 2    | 2   | 11  | 11  | 3   | 2   | 2   | 5   | 2   | 7   | 2   | 1    | 1    | 1    | 2    | 2    | 1    | 2    | 1    | 1    | 2    | 1    | 2    | 1    | 1    | 2    | 2    | 2   | 3   | 3   | 3   | 3   | \-3 | 2    | 2    | 1    | 2    | 1    | 3    | 3    | 2    | 3    | 3    | 2    | 1    | 1    | 1    | 1    | 5   | 1   | 0    | 1    | 1    | 0    | 1    | 0    | 3   | 0    | 0    | 0    | 1    | 0    | 1    | 3    | 2    | 2    | 1    | 1    | 1    | 1    | 1    | 1    | 1    |
| keep | 14445532 |       1 | 1  | NA   | 1  | 1  | 1  | 5  | 8  | 2   | 1   | 3   | 11  | \-3 | \-3 | \-3 | \-3 | 3   | 3   | 5   | 8   | 3   | 1    | 3    | 4    | 4    | 4    | 4    | 1    | 3    | 2    | 2    | 2    | 2    | 2    | 3    | 3    | 2    | 2    | 4   | 4   | 1    | 1    | 1    | 1    | 2    | 2   | 11  | 11  | 3   | 2   | 2   | 5   | 2   | 7   | 2   | 1    | 1    | 1    | 2    | 2    | 1    | 2    | 1    | 1    | 2    | 1    | 2    | 1    | 1    | 2    | 2    | 2   | 3   | 3   | 3   | 3   | \-3 | 2    | 2    | 1    | 2    | 1    | 3    | 3    | 2    | 3    | 3    | 2    | 1    | 1    | 1    | 1    | 5   | 1   | 0    | 1    | 1    | 0    | 1    | 0    | 3   | 0    | 0    | 0    | 1    | 0    | 1    | 3    | 2    | 2    | 1    | 1    | 1    | 1    | 1    | 1    | 1    |
| keep | 14445527 |       5 | 2  | NA   | 2  | 1  | 1  | 4  | 8  | 1   | \-3 | \-3 | \-3 | 3   | 1   | 4   | 8   | \-3 | \-3 | \-3 | \-3 | NA  | 3    | 1    | 2    | 2    | 5    | 5    | 5    | 5    | 2    | 4    | 1    | 4    | 3    | 4    | 4    | 4    | 4    | 3   | 3   | 1    | 4    | 4    | 4    | 1    | NA  | 10  | 3   | 2   | 2   | 1   | 5   | 2   | 3   | 1   | 1    | 1    | 1    | 1    | 2    | 2    | 1    | 1    | 1    | 2    | 2    | 2    | 1    | 1    | 2    | 2    | 1   | 1   | 3   | 3   | NA  | NA  | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 6   | 1   | 1    | 1    | 1    | 0    | 0    | 0    | 2   | 0    | 0    | 0    | 1    | 0    | 1    | 3    | 3    | 3    | 3    | 3    | 3    | 2    | 3    | 3    | 3    |
| drop | 14445527 |      12 | 2  | NA   | 2  | 1  | 1  | 4  | 8  | 1   | \-3 | \-3 | \-3 | 3   | 1   | 4   | 8   | \-3 | \-3 | \-3 | \-3 | NA  | 3    | 1    | 2    | 2    | 5    | 5    | 5    | 5    | 2    | 4    | 1    | 4    | 2    | 4    | 4    | 4    | 4    | 3   | 3   | 1    | 4    | 4    | 4    | 1    | NA  | 10  | 3   | 2   | 2   | 1   | 5   | 2   | 3   | 1   | 1    | 1    | 1    | 1    | NA   | NA   | 1    | 1    | 1    | NA   | NA   | NA   | 1    | 1    | NA   | NA   | 1   | 1   | 3   | 3   | NA  | NA  | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 6   | 1   | 1    | 1    | 1    | 0    | 0    | 0    | 2   | 0    | 1    | 0    | 1    | 0    | 1    | 3    | 3    | 3    | 3    | 3    | 3    | 2    | 3    | 3    | 3    |
| keep | 14445343 |       2 | 2  | 1978 | 2  | 1  | 3  | 2  | 9  | 1   | \-3 | \-3 | \-3 | 3   | 3   | 1   | 8   | \-3 | \-3 | \-3 | \-3 | 6   | 3    | 1    | 2    | 4    | 1    | 1    | 1    | 5    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 3   | 3   | 2    | 1    | 1    | 2    | 2    | 2   | 5   | 11  | 3   | 1   | 2   | 5   | 2   | 5   | 2   | 1    | 1    | 2    | 1    | 1    | 1    | 2    | 1    | 1    | 2    | 1    | 2    | 1    | 1    | 2    | 2    | 1   | 1   | 1   | 4   | NA  | NA  | 1    | 3    | 3    | 3    | 1    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 4   | 3   | 0    | 1    | 0    | 0    | 0    | 0    | 4   | 0    | 1    | 0    | 0    | 0    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    |
| drop | 14445343 |       8 | 2  | 1978 | 2  | 1  | 3  | 2  | 9  | 1   | \-3 | \-3 | \-3 | 3   | 3   | 1   | 8   | \-3 | \-3 | \-3 | \-3 | 6   | 3    | 1    | 2    | 4    | 1    | 1    | 1    | 5    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 4    | 3   | 3   | 2    | 1    | 1    | 2    | 2    | 2   | 5   | 11  | 3   | 1   | 2   | 5   | 2   | 5   | 2   | 1    | 1    | NA   | 1    | 1    | 1    | NA   | 1    | 1    | NA   | 1    | NA   | 1    | 1    | NA   | NA   | 2   | 1   | 1   | 4   | NA  | NA  | 1    | 3    | 3    | 3    | 1    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 4   | 3   | 0    | 1    | 0    | 0    | 0    | 0    | 4   | 0    | 1    | 0    | 0    | 0    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    |
| drop | 14444429 |       1 | 1  | 1989 | 1  | 1  | 1  | 4  | 4  | 1   | \-3 | \-3 | \-3 | \-3 | \-3 | \-3 | \-3 | 2   | 3   | 4   | 5   | 5   | 3    | 3    | 1    | 5    | 2    | 2    | 1    | 2    | 1    | 2    | 2    | 1    | 1    | 3    | 3    | 1    | 1    | 4   | 4   | 1    | 2    | 1    | 1    | 1    | 2   | 11  | 4   | 3   | 6   | 2   | 4   | 2   | 3   | 2   | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 2    | 1    | 2    | 1    | 1    | 2    | 2    | 2   | 1   | 3   | 3   | 2   | \-3 | 3    | 3    | 3    | NA   | 1    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 4   | 1   | 0    | 1    | 0    | 0    | 0    | 0    | 2   | 1    | 0    | 0    | 0    | 0    | 1    | 1    | 1    | 1    | 1    | 1    | 3    | 4    | 4    | 1    | 1    |
| keep | 14444429 |       0 | 1  | 1989 | 1  | 1  | 1  | 4  | 4  | 1   | \-3 | \-3 | \-3 | \-3 | \-3 | \-3 | \-3 | 2   | 3   | 4   | 5   | 5   | 3    | 3    | 1    | 5    | 2    | 2    | 1    | 2    | 1    | 2    | 2    | 1    | 1    | 3    | 3    | 1    | 1    | 4   | 4   | 1    | 2    | 1    | 1    | 1    | 2   | 11  | 4   | 3   | 6   | 2   | 4   | 2   | 3   | 2   | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 1    | 2    | 1    | 2    | 1    | 1    | 2    | 2    | 2   | 1   | 3   | 3   | 2   | \-3 | 3    | 3    | 3    | 3    | 1    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 3    | 4   | 1   | 0    | 1    | 0    | 0    | 0    | 0    | 2   | 1    | 0    | 0    | 0    | 0    | 1    | 1    | 1    | 1    | 1    | 1    | 3    | 4    | 4    | 1    | 1    |

基于这个结构，脑补一下填补过程：

  - `group_by(ID, missing)` 本身没有意义，只是为了看一眼数据

  - 两个fill的操作作用是充分填补所有缺失

  - `group_by(ID) %>%
slice_min(missing)`

这一步是在填补后的基础上，对每个ID的人，只保留它原始missing数最少的那条。由于上一步已经充分填补了所有条目，这一步选出来任何一条其实都是尽可能填补好的。进过slice\_min后，大多数ID只会保留一条记录。但到这一步还不够，因为对某些ID来说，可能存在多个missing数本就相同的记录，这样的话即使我们用slice\_min只保留missing数最少的记录，对于同一个ID来说，很有可能还是会保留2或2个以上的记录。

下一步，我们需要删除一些多余的记录，实现对每个ID只保留一个记录即可。

  - `group_by(ID) %>%
slice(1)`

这一步是对每个ID的人，只保留一条记录。所有ID最终都只会有一行记录。最终一共316人。这一步看起来会有些跳跃，实际上没有问题，因为它只对同一ID下，missing数相同的多个记录起作用。若多个记录的missing数均为0，任意保留一个都是对的；若多个记录的missing数均不为0却相等，我们需要做的是随机保留一条即可。由于之前已经充分填补过，所以随机保留任何一条结果都是等效的。
